Add possibility of having multiple pointers canceled by user agents
w3c/pointerevents pull request #233
Opened 2018-03-21 14:55 UTC by NavidZ

Closes #226.

2018-03-22 15:00 UTC, mustaqahmed requested changes

2018-03-22 15:00 UTC, mustaqahmed commented on index.html
> +                     <div class="note">User agents can use multiple pointers for a particular action like scrolling or zooming.
Please emphasize pointer _types_.  Something like:
> User agents can trigger panning or zooming through multiple pointer types (say "touch" and "pen"), and therefore can possibly cancel all pointers of those types for a single viewport manipulation.

2018-03-22 15:00 UTC, mustaqahmed commented on index.html
> +                     In that case they can cancel all the pointers they deem necessary.</div></li>
Nit: the indentation looks odd around here.  Please unindent by 1 char here and Lines 567-570.

2018-03-22 17:59 UTC, mustaqahmed commented on index.html
> +                     In that case they can cancel all the pointers they deem necessary.</div></li>
Just realized that the diff viewer in github doesn't isolate whitespace changes.  So let's not change whitespaces here.

2018-03-28 14:35 UTC, patrickhlauke requested changes

2018-03-28 14:35 UTC, patrickhlauke commented on index.html
> +                     <div class="note">User agents can trigger panning or zooming through multiple pointer types (say "touch" and "pen"),
"(say "touch" or "pen")" may sound better as "(such as touch and pen)"

2018-03-28 14:35 UTC, patrickhlauke commented on index.html
> +                     and therefore can possibly cancel all pointers of those types for a single viewport manipulation.</div</li>
i'd reword the whole "and therefore...manipulation" to "and therefore the start of a pan or zoom action may result in the cancellation of various pointers, including pointers with different pointer types." or similar. Seems a bit clearer (assuming I understood this right)

2018-03-28 14:44 UTC, patrickhlauke commented on index.html
> +                     <div class="note">User agents can trigger panning or zooming through multiple pointer types (say touch and pen),
nitpick: i'd still change "say" to "such as" (the former sounds a tad too informal/colloquial)

2018-03-28 14:50 UTC, patrickhlauke approved these changes

2018-03-28 17:51 UTC, mustaqahmed approved these changes

2018-03-28 17:54 UTC, merged