Add single-directional touch action values
w3c/pointerevents pull request #294
Opened 2019-08-06 17:59 UTC by NavidZ

2019-08-06 18:03 UTC, NavidZ commented
@smaug---- @BoCupp-Microsoft @graouts @patrickhlauke any feedback is appreciated.
This feature was already implemented/shipped in Chrome like 2 years ago and you can give it a try there if you like.

@plehegar, @patrickhlauke I changed the PE level to version 3 in this pull request and added links and whatnot to PEv2. Let me know if we are planning it some other way or whether it is alright from W3C point of view to have it like this. I assumed the published version of V2 is already hosted as an html file and has nothing to do with the top commit of this repo. So we can just change the code here and move to the V3. But feel free to correct me if I'm wrong. I can change this PL to whatever you suggest.

2019-08-06 22:06 UTC, patrickhlauke commented
changed this to use pe3 as base branch - just so we can work on integrating the extension stuff and touch action values etc into it and then plop the v3 rough version into gh-pages in one fell swoop (not that it makes much of a difference i guess)

2019-08-07 15:37 UTC, patrickhlauke commented
discussed in PEWG call today, no point working separately in pe3 branch. we'll just do it straight in gh-pages...

2019-08-16 15:29 UTC, NavidZ commented
@smaug---- @BoCupp-Microsoft @graouts any objections/comments regarding the new values? Can we merge this PR as is?

2019-08-19 09:03 UTC, graouts requested changes

2019-08-19 09:03 UTC, graouts commented on index.html
> +           Level 3 includes editorial clarifications, new features to enable more use cases, in an effort to enable wider developer and browser adoption.</p>
This change does not seem relevant to the new single-directional touch-action values. I think they should be moved to a different PR.

2019-08-29 15:49 UTC, patrickhlauke approved these changes

2019-08-29 15:49 UTC, merged

2019-08-29 16:04 UTC, NavidZ commented
@graouts this seems to be merged now. But feel free to still review the change and we can still incorporate your feedback if you don't agree with the current proposal.

2019-08-29 16:07 UTC, patrickhlauke commented
oh sorry, i just assumed that since @graouts' comment was only related to the out-of-scope changes in this PR, that he was ok with the rest. if that wasn't the case, apologies Antoine

2019-08-30 14:10 UTC, graouts commented
No worries, you assumed correctly.

2022-11-23 15:45 UTC, mustaqahmed commented
We already have the following WPTs covering this PR: `pointerevent_touch-action-pan-{left,right,up,down}-css_touch.html`.