Expand explanation for compatibility mouse events
w3c/pointerevents pull request #459
Opened 2022-10-24 23:05 UTC by patrickhlauke

* Explain the rationale/thinking behind compat events (to represent a consistent legacy mouse pointer)
* Add note about high level "interleaved" events, and the reality of what user agents may do, especially on touchscreens, as long as the relative order is consistent

Closes #454

2022-10-24 23:12 UTC, patrickhlauke commented
I think this PR addresses the actual question of #454 (basically, that the exact sequence of when a compat mouse event fires in relation to a pointer event is undefined and left up to UAs, as long as the overall relative order reflects a consistent legacy mouse pointer).

https://github.com/w3c/pointerevents/pull/458 tacles a slightly separate, but related, issue (since the original question of #454 was not about touch, but mouse). Will review/merge this separately

2022-10-26 20:01 UTC, mustaqahmed requested changes
Thanks, this is looking great.  I am requesting a minor change to clarify an easy "batching" case...something along the lines of what we discussed in our group meeting few weeks ago.

2022-10-26 20:01 UTC, mustaqahmed commented on index.html
> +            <p>Particularly in the case of touchscreen inputs, user agents MAY apply additional heuristics for gesture recognition (unless explicitly suppressed by authors through <a><code>touch-acti
Perhaps clarify further what "after `pointerup`" mean.  My suggestion is to rephrase the second sentence in this para to something like this:

> During a sequence of events between a `pointerdown` event and a `pointerup` event, the gesture recognition may have to wait until the `pointerup` event to detect or ignore a gesture, and as a result the compatibility mouse events for the whole sequence may be dispatched together after the last `pointerup` event.

2022-10-26 20:29 UTC, patrickhlauke commented on index.html
> +            <p>Particularly in the case of touchscreen inputs, user agents MAY apply additional heuristics for gesture recognition (unless explicitly suppressed by authors through <a><code>touch-acti
Tweaked slightly, but yes looking good. Thanks for the suggestion.

2022-10-27 17:47 UTC, mustaqahmed approved these changes
LGTM, thanks.  I will land it now.

2022-10-27 17:52 UTC, merged