Update boundary event behavior for a stationary pointing device.
w3c/pointerevents pull request #532
Opened 2024-12-17 16:20 UTC by mustaqahmed

PEWG decided in #529 that the PointerEvents spec should match the UIEvent spec behavior for non-moving pointing device: boundary events should fire after a layout change, and no move events should fire.

2024-12-18 16:45 UTC, smaug---- commented
@masayuki-nakano you may have some opinion on the pr

2025-01-14 16:43 UTC, flackr commented on index.html
> +                    <li>A <a data-lt="events-from-layout-changes">layout change</a> causes the <a>hit test</a> boundaries of an element to move underneath an uncaptured primary pointer of a stationar
Why do you call out "primary pointer" here? I think that any uncaptured pointer is supposed to generate boundary events, right? https://w3c.github.io/pointerevents/#the-pointerover-event

2025-01-14 16:43 UTC, flackr commented on index.html
> +                <div class="note">This event type is similar to {{GlobalEventHandlers/pointerout}} but with two differences: {{GlobalEventHandlers/pointerleave}} does not bubble, and its dispatch con
nit: I prefer the originaly terminology for referring to the descendants, i.e. "boundaries of all of its descendant elements".

2025-01-14 16:43 UTC, flackr commented on index.html
> +                    <li>A pointing device is moved into the <a>hit test</a> boundaries of an element.  Note that <code>setPointerCapture()</code> or <code>releasePointerCapture()</code> might have ch
Instead of calling out the hit test boundary and interaction with capture, it seems like we should refer to the generic targeting of pointerevents, e.g. the target determination in https://w3c.github.io/pointerevents/#firing-events-using-the-pointerevent-interface which already has taken this and capture into account.

2025-01-14 22:08 UTC, mustaqahmed commented on index.html
> +                    <li>A <a data-lt="events-from-layout-changes">layout change</a> causes the <a>hit test</a> boundaries of an element to move underneath an uncaptured primary pointer of a stationar
The UI Event spec currently mentions that the stationary device boundary events come only from the "primary pointing device", e.g. see the [mouseeneter](https://w3c.github.io/uievents/#event-type-mouseenter) section.

I can imagine this was done to minimize event-dispatch related overhead for a stationary device but not sure.  Any chance over effect is limited to primary (first) touch pointer?

2025-01-14 22:38 UTC, mustaqahmed commented on index.html
> +                <div class="note">This event type is similar to {{GlobalEventHandlers/pointerout}} but with two differences: {{GlobalEventHandlers/pointerleave}} does not bubble, and its dispatch con
The normative points above still mentions "all descendants".  In this non-normative text, I wanted to highlight only the main difference, i.e., whether descendants are considered or not.

See the very similar note above for `pointerenter`: it was about "one descendant".

2025-01-15 15:53 UTC, mustaqahmed commented on index.html
> +                    <li>A pointing device is moved into the <a>hit test</a> boundaries of an element.  Note that <code>setPointerCapture()</code> or <code>releasePointerCapture()</code> might have ch
You are right, this is all about generic targeting.  I can easily refer to Sec4.1.3 for `pointerover` and `pointerout` but the same becomes tricky for `pointerenter` and `pointerleave` because of the involvement of descendant element boundaries here.  Any suggestions?

2025-01-15 15:59 UTC, mustaqahmed commented on index.html
> +                    <li>A <a data-lt="events-from-layout-changes">layout change</a> causes the <a>hit test</a> boundaries of an element to move underneath an uncaptured primary pointer of a stationar
On Android, the hover effect is shown only for the primary touch pointer (and it vanishes at the moment a non-primary touch pointer becomes active).

2025-01-15 16:30 UTC, flackr commented on index.html
> +                    <li>A pointing device is moved into the <a>hit test</a> boundaries of an element.  Note that <code>setPointerCapture()</code> or <code>releasePointerCapture()</code> might have ch
It's still the same thing, just if the target is any of the inclusive descendants rather than just the element itself.

E.g. for pointerleave it's if the determined target of the pointer is any of the inclusive descendants of the element.

2025-01-15 17:13 UTC, mustaqahmed commented on index.html
> +                    <li>A pointing device is moved into the <a>hit test</a> boundaries of an element.  Note that <code>setPointerCapture()</code> or <code>releasePointerCapture()</code> might have ch
Great suggestion!  Done.

2025-01-16 02:26 UTC, masayuki-nakano requested changes

2025-01-16 02:26 UTC, masayuki-nakano commented on index.html
> +                <p>A pointing device that moved relative to the screen surface or underwent some change in any of its properties fires various events as defined in <a>Pointer Event types</a>.  For a
> The user agent MAY delay the firing of these boundary events because of performance reasons (e.g. to avoid too many hit-tests or layout changes caused by boundary event listeners).

I think it should be defined here that if the last `pointerover` target appears under the pointer after temporarily removed. I think `pointerover` should be fired again to avoid the timing issue of the delay vs. async handling in web apps.  Otherwise, we could see another issue which is the case when the last `pointerover` target is back under the pointer but some ancestor elements which got `pointerenter` events fired are not back again.

(It's fine to handle this in a new issue.)

2025-01-28 22:01 UTC, mustaqahmed commented on index.html
> +                <p>A pointing device that moved relative to the screen surface or underwent some change in any of its properties fires various events as defined in <a>Pointer Event types</a>.  For a
I totally agree this PR is unclear about such DOM modifications.  Let's fix it separately after this PR lands.

I think the proper way to address such cases would be introducing a state variable for "current element under pointer" for each pointer, and dispatch boundary events whenever this changes.  That will also help us port the [Mouse Event Order](https://w3c.github.io/uievents/#events-mouseevent-event-order) section from UIEvent into PoitnerEvent spec (which will nicely cover a part of our TPAC 2024 plan).

2025-01-29 03:33 UTC, masayuki-nakano approved these changes
Putting off to fix my concern in the separate issue. So, I'm now fine with the change.

2025-01-29 15:51 UTC, mustaqahmed commented
> Putting off to fix my concern in the separate issue. So, I'm now fine with the change.

Thanks.  I just linked this to #520, let's continue the discussion there.

2025-01-29 20:55 UTC, mustaqahmed commented on index.html
> +                    <li>A <a data-lt="events-from-layout-changes">layout change</a> causes the <a>hit test</a> boundaries of an element to move underneath an uncaptured primary pointer of a stationar
Removed "primary" as per PEWG discussion today.

2025-01-29 21:08 UTC, merged